BREEZE_SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BREEZE_ROOT="$(cd "${BREEZE_SCRIPTS}/.." && pwd)"
export BREEZE_ROOT
export BREEZE_CODE="${BREEZE_CODE:-${BREEZE_ROOT}/breeze-tts}"
export BREEZE_CKPT="${BREEZE_CKPT:-${BREEZE_ROOT}/checkpoints/Breeze-TTS-2}"
export BREEZE_VENV="${BREEZE_VENV:-${BREEZE_ROOT}/.venv}"
export BREEZE_REPO="${BREEZE_REPO:-https://github.com/breezeblue-ai/breeze-tts.git}"
export BREEZE_MODEL_ID="${BREEZE_MODEL_ID:-BreezeBlue/Breeze-TTS-2}"
export TORCH_BLAS_PREFER_HIPBLASLT="${TORCH_BLAS_PREFER_HIPBLASLT:-1}"
export HIP_VISIBLE_DEVICES="${HIP_VISIBLE_DEVICES:-0}"
export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-7860}"
export AMD_TORCH_INDEX="${AMD_TORCH_INDEX:-https://repo.amd.com/rocm/whl-multi-arch/}"
export AMD_TORCH="${AMD_TORCH:-torch[device-gfx1151]==2.12.0+rocm7.14.0}"
export AMD_TORCHVISION="${AMD_TORCHVISION:-torchvision[device-gfx1151]==0.27.0+rocm7.14.0}"
export AMD_TORCHAUDIO="${AMD_TORCHAUDIO:-torchaudio==2.11.0+rocm7.14.0}"
export UV_PYTHON="${UV_PYTHON:-${PYTHON:-3.12}}"
